# Cryptotrader - Cryptocurrency Trader Agent and Agent Development Environment

THIS REPOSITORY CONTAINS A CRYPTOCURRENCY DEVELOPMENT, BACKTESTING AND TRADING ENVIRONMENT, AS WELL AS APRIORI AND
MACHINE LEARNING AGENTS FOR CRYPTOCURRENCY ARBITRAGE.
IT IS DISTRIBUTED UNDER CREATIVE COMMONS LICENCE AND IS SHIPPED "AS IS" WITH NO ASSURANCES WHATSOEVER.

IT IS UNDER ACTIVE DEVELOPMENT AND IN PRE ALPHA STAGE.

MAINTAINER: TAU

